version: '3.4'

services:
  nodeserver:
    image: nodeserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8383:8383
