version: '3.4'

services:
  nodeserver:
    image: nodeserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8383:8383
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
